var api = {
    ds: {

        approvalType: {url: "ds/approvalType.json", demo: true},
        activityInfo: {url: "ds/activityInfo.json", demo: true},
        accountType: {url: "ds/accountType.json", demo: true},
        backVisitGrade: {url: "ds/backVisitGrade.json", demo: true},
        bankType: {url: "ds/bankType.json", demo: true},
        companyType: {url: "ds/companyType.json", demo: true},
        checkBankName: {url: "ds/checkBankName.json", demo: true},
        constructionInfo: {url: "ds/constructionInfo.json", demo: true},
        couponType: {url: "ds/couponType.json", demo: true},
        customerInfo: {url: "ds/customerInfo.json", demo: true},
        decorationInfo: {url: "ds/decorationInfo.json", demo: true},
        deductType: {url: "ds/deductType.json", demo: true},
        departmentInfo: {url: "ds/departmentInfo.json", demo: true},
        drawLineInfo: {url: "ds/drawLineInfo.json", demo: true},
        houseInfo: {url: "ds/houseInfo.json", demo: true},
        logType: {url: "ds/logType.json", demo: true},
        materialInfo: {url: "ds/materialInfo.json", demo: true},
        personInfo: {url: "ds/personInfo.json", demo: true},
        quotationInfo: {url: "ds/quotationInfo.json", demo: true},
        salaryType: {url: "ds/salaryType.json", demo: true},
        workType: {url: "ds/workType.json", demo: true},

    }, index: {

        approvalTrackIndex: {url: "/views/approval/approvalTrack.html"},
        userApproveIndex: {url: "/views/approval/userApprove.html"},

        decorationOrderAuditIndex: {url: "/views/audit/decorationOrder.html"},
        decorationOrderDetailAuditIndex: {url: "/views/audit/decorationOrderDetail.html"},
        auditIndex: {url: "/views/audit/audit.html"},
        budgetAddOrReduceItemIndex: {url: "/views/audit/addOrReduceItems.html"},
        chargebackIndex: {url: "/views/audit/chargeback.html"},

        supervisionIndex: {url: "/views/construction/supervision.html"},
        supervisionDetailIndex: {url: "/views/construction/supervisionDetail.html"},
        supervisionInDecreaseIndex: {url: "/views/construction/supervisionInDecrease.html"},

        reworkIndex: {url: "/views/construction/rework.html"},

        onsiteInspectionRecordIndex: {url: "/views/construction/onsiteInspectionRecord.html"},
        onsiteInspectionDeductionIndex: {url: "/views/construction/onsiteInspectionDeduction.html"},

        qualityTestingIndex: {url: "/views/construction/qualityTesting.html"},
        qualityTestingDetailIndex: {url: "/views/construction/qualityTestingDetail.html"},
        qualityTestingRecordIndex: {url: "/views/construction/qualityTestingRecord.html"},

        customerServiceIndex: {url: "/views/construction/customerService.html"},
        customerServiceDetailIndex: {url: "/views/construction/customerServiceDetail.html"},

        drawLineApplyIndex: {url: "/views/drawLine/drawLineApply.html"},
        drawLineDeploymentIndex: {url: "/views/drawLine/drawLineDeployment.html"},
        drawLinePersonInfoIndex: {url: "/views/drawLine/drawLinePersonInfo.html"},

        inspectionIndex: {url: "/views/construction/inspection.html"},
        inspectionDeductionIndex: {url: "/views/construction/inspectionDeduction.html"},
        inspectionRecordIndex: {url: "/views/construction/inspectionRecord.html"},

        acceptanceIndex: {url: "/views/construction/acceptance.html"},
        acceptanceDetailIndex: {url: "/views/construction/acceptanceDetail.html"},

        customerServiceBackVisitIndex: {url: "/views/construction/customerServiceBackVisit.html"},
        customerServiceComplaintIndex: {url: "/views/construction/customerServiceComplaint.html"},
        customerServiceGuaranteeIndex: {url: "/views/construction/customerServiceGuarantee.html"},

        supervisionReworkIndex: {url: "/views/construction/supervisionRework.html"},
        supervisionAddReduceIndex: {url: "/views/construction/supervisionAddReduce.html"},
        supervisionReworkDrawingIndex: {url: "/views/construction/supervisionReworkDrawing.html"},

        workerAllocationIndex: {url: "/views/construction/workerAllocation.html"},
        workerAllocationDetailIndex: {url: "/views/construction/workerAllocationDetail.html"},

        categoryIndex: {url: "/views/data/category.html"},
        brandIndex: {url: "/views/data/brand.html"},
        customerIndex: {url: "/views/data/customer.html"},
        villageIndex: {url: "/views/data/village.html"},

        addReduceIndex: {url: "/views/decoration/addReduce.html"},
        addReduceDetailIndex: {url: "/views/decoration/addReduceDetail.html"},
        addReduceOutputIndex: {url: "/views/decoration/addReduceOutput.html"},

        decorationOrderDesignerIndex: {url: "/views/decoration/decorationOrderDesigner.html"},
        decorationOrderDesignerDetailIndex: {url: "/views/decoration/decorationOrderDesignerDetail.html"},

        decorationOrderSalesmanIndex: {url: "/views/decoration/decorationOrderSalesman.html"},

        decorationOrderCommonIndex: {url: "/views/decoration/decorationOrderCommon.html"},
        decorationOrderCommonDetailIndex: {url: "/views/decoration/decorationOrderCommonDetail.html"},

        decorationOrderAdvanceIndex: {url: "/views/decoration/decorationOrderAdvance.html"},
        decorationOrderAdvanceDetailIndex: {url: "/views/decoration/decorationOrderAdvanceDetail.html"},

        decorationActivityIndex: {url: "/views/decoration/decorationActivity.html"},
        decorationActivityItemIndex: {url: "/views/decoration/decorationActivityItem.html"},

        decorationOrderBelongIndex: {url: "/views/decoration/decorationOrderBelong.html"},
        decorationOrderBelongDetailIndex: {url: "/views/decoration/decorationOrderBelongDetail.html"},
        decorationOrderBelongInfoIndex: {url: "/views/decoration/decorationOrderBelongInfo.html"},

        decorationOrderBackVisitIndex: {url: "/views/decoration/decorationOrderBackVisit.html"},
        backVisitIndex: {url: "/views/decoration/backVisit.html"},
        createOrderIndex: {url: "/views/decoration/createOrder.html"},

        designRegionIndex: {url: "/views/department/designRegion.html"},
        businessRegionIndex: {url: "/views/department/businessRegion.html"},
        designDeptIndex: {url: "/views/department/designDept.html"},
        businessDeptIndex: {url: "/views/department/businessDept.html"},
        materialDeptIndex: {url: "/views/department/materialDept.html"},
        engineeringDeptIndex: {url: "/views/department/engineeringDept.html"},
        dutyDeptIndex: {url: "/views/department/dutyDept.html"},

        decorationPaymentIndex: {url: "/views/payment/decorationPayment.html"},
        changeItemIndex: {url: "/views/payment/changePaymentItem.html"},
        decorationPaymentCheckIndex: {url: "/views/payment/decorationPaymentCheck.html"},
        decorationPaymentReceiptIndex: {url: "/views/payment/decorationPaymentReceipt.html"},

        materialPaymentIndex: {url: "/views/payment/materialPayment.html"},
        materialPaymentReceiptIndex: {url: "/views/payment/materialPaymentReceipt.html"},
        materialPaymentCheckIndex: {url: "/views/payment/materialPaymentCheck.html"},

        materialOutsideCheckIndex: {url: "/views/payment/materialOutsideCheck.html"},

        paymentIndex: {url: "/views/payment/payment.html"},
        paymentCheckIndex: {url: "/views/payment/paymentCheck.html"},
        paymentReceiptIndex: {url: "/views/payment/paymentReceipt.html"},

        messageIndex: {url: "/views/information/messageMng.html"},
        moreNoticesIndex: {url: "/views/information/moreNotices.html"},
        noticeIndex: {url: "/views/information/noticeMng.html"},
        activityIndex: {url: "/views/information/activity.html"},
        activityItemIndex: {url: "/views/information/activityItem.html"},

        actionLogIndex: {url: "/views/log/actionLog.html"},
        loginLogIndex: {url: "/views/log/loginLog.html"},

        mapIndex: {url: "/views/map/index.html"},

        materialModelIndex: {url: "/views/material/materialModel.html"},

        materialBrandRightIndex: {url: "/views/material/materialBrandRight.html"},
        materialBalanceValueIndex: {url: "/views/material/materialBalanceValue.html"},
        materialSaleOrderIndex: {url: "/views/material/materialSaleOrder.html"},
        materialOrderIndex: {url: "/views/material/materialOrder.html"},
        materialSubOrderIndex: {url: "/views/material/materialSubOrder.html"},
        materialSubOrderAddIndex: {url: "/views/material/materialSubOrderAdd.html"},
        materialSubOrderDetailIndex: {url: "/views/material/materialSubOrderDetail.html"},
        materialSubOrderCollectionIndex: {url: "/views/material/materialSubOrderCollection.html"},
        materialSubOrderRefundIndex: {url: "/views/material/materialSubOrderRefund.html"},
        materialSubOrderReceipt: {url: "/views/material/materialSubOrderReceipt.html"},
        materialOrderPreBalanceIndex: {url: "/views/material/materialOrderPreBalance.html"},
        materialOrderPreBalanceDetailIndex: {url: "/views/material/materialOrderPreBalanceDetail.html"},
        materialOrderArrivalIndex: {url: "/views/material/materialOrderArrival.html"},
        materialOrderArrivalDetailIndex: {url: "/views/material/materialOrderArrivalDetail.html"},
        materialOrderPostBalanceIndex: {url: "/views/material/materialOrderPostBalance.html"},
        materialOrderPostBalanceDetailIndex: {url: "/views/material/materialOrderPostBalanceDetail.html"},
        materialOutsideIndex: {url: "/views/material/materialOutside.html"},

        materialInsideIndex: {url: "/views/material/materialInside.html"},
        materialInsidePaymentIndex: {url: "/views/payment/materialInsidePayment.html"},
        materialInsidePaymentCheckIndex: {url: "/views/payment/materialInsidePaymentCheck.html"},

        userIndex: {url: "/views/personnel/user.html"},
        userEditIndex: {url: '/views/personnel/userEdit.html'},
        userContractIndex: {url: "/views/personnel/userContract.html"},
        userExperienceIndex: {url: "/views/personnel/userExperience.html"},
        userSalaryIndex: {url: "/views/payment/userSalary.html"},

        functionAreaIndex: {url: "/views/quotation/functionArea.html"},
        quotationItemIndex: {url: "/views/quotation/quotationItem.html"},
        quotationVersionIndex: {url: "/views/quotation/quotationVersion.html"},
        systemDefineItemIndex: {url: "/views/quotation/systemDefineItem.html"},

        quotationIndex: {url: "/views/quotation/quotationIndex.html"},
        quotationDetailIndex: {url: "/views/quotation/quotationDetail.html"},
        quotationOutputIndex: {url: "/views/quotation/quotationOutput.html"},

        reportBizDeptIndex: {url: "/views/report/reportBizDept.html"},
        reportDesignDeptIndex: {url: "/views/report/reportDesignDept.html"},
        reportBizRegionIndex: {url: "/views/report/reportBizRegion.html"},
        reportDesignRegionIndex: {url: "/views/report/reportDesignRegion.html"},
        materialDepartmentReportIndex: {url: "/views/report/materialDepartmentReport.html"},
        materialDesignReportIndex: {url: "/views/report/materialDesignReport.html"},
        materialMerchantReportIndex: {url: "/views/report/materialMerchantReport.html"},
        rankIndex: {url: "/views/report/rank.html"},

        designerSalaryIndex: {url: "/views/salary/designerSalary.html"},
        designerBalanceSalaryIndex: {url: "/views/salary/designerBalanceSalary.html"},
        designerOutsideSalaryIndex: {url: "/views/salary/designerOutsideSalary.html"},
        designerDeductSalaryIndex: {url: "/views/salary/designerDeductSalary.html"},
        venderBalanceIndex: {url: "/views/salary/venderBalance.html"},
        workerSalaryIndex: {url: "/views/salary/workerSalary.html"},
        workerBaseSalaryScheduleIndex: {url: "/views/salary/workerBaseSalarySchedule.html"},
        workerBaseSalaryScheduleDetailIndex: {url: "/views/salary/workerBaseSalaryScheduleDetail.html"},
        workerDeductSalaryScheduleDetailIndex: {url: "/views/salary/workerDeductSalaryScheduleDetail.html"},
        workerBaseSalaryIndex: {url: "/views/salary/workerBaseSalary.html"},
        workerDeductSalaryIndex: {url: "/views/salary/workerDeductSalary.html"},

        cityIndex: {url: "/views/system/city.html"},
        cityProperIndex: {url: "/views/system/cityProper.html"},
        regionIndex: {url: "/views/system/region.html"},
        roleIndex: {url: "/views/system/role.html"},
        roleActionIndex: {url: "/views/system/roleRight.html"},
        subFunctionActionIndex: {url: "/views/system/subFunctionAction.html"},
        userProfile: {url: "/views/system/userProfile.html"},
        changePasswordIndex: {url: "/views/system/changePassword.html"},
        resetPasswordIndex: {url: "/views/system/resetPassword.html"},
        versionIndex: {url: "/version.html"},
        faqIndex: {url: "/faq.html"},

    }, common: {

        QRCode: {url: "QRCode.json", demo: true},
        wmCode: {url: "wmCode.json", demo: true},

        createTree: {url: "createTree.json", demo: true},

        logout: {url: "logout.json"},

        pageBuildingNameRule: {url: "pageBuildingNameRule.json"},
        queryBuildingNameRule: {url: "queryBuildingNameRule.json", demo: true},

        queryMeasurementUnit: {url: "queryMeasurementUnit.json", demo: true},

        queryWorkType: {url: "queryWorkType.json", demo: true},

        pageReceiptType: {url: "pageReceiptType.json"},
        queryReceiptType: {url: "queryReceiptType.json", demo: true},
        queryReceiptTypeByType: {url: "queryReceiptTypeByType.json"},
        addReceiptType: {url: "addReceiptType.json", server: "communionServer"},

        changeDecorationOrderForOrderId: {url: "changeDecorationOrderForOrderId.json"},
        changeDecorationOrderForTime: {url: "changeDecorationOrderForTime.json"},
        changeDecorationOrderForVersionId: {url: "changeDecorationOrderForVersionId.json"},
        changeDecorationOrderForStatus: {url: "changeDecorationOrderForStatus.json"},
        changeDecorationPaymentForTime: {url: "changeDecorationPaymentForTime.json"},
        refundDecorationPaymentForManage: {url: "refundDecorationPaymentForManage.json"},
        changeMaterialSubOrderForOrderId: {url: "changeMaterialSubOrderForOrderId.json"},
        changeMaterialPaymentForTime: {url: "changeMaterialPaymentForTime.json"},
        subDecorationOrderForQuotationTime: {url: "subDecorationOrderForQuotationTime.json"},
        updateQuotationFunctionAreaItemByQuotationIdAType: {url: "updateQuotationFunctionAreaItemByQuotationIdAType.json"},

        exportMaterialPayment: {url: "exportMaterialPayment.json"},

        showImg: {url: "showImg.json"},
        downloadFile: {url: "downloadFile.json"},
        uploadImg: {url: "uploadImg.json"},
        uploadOther: {url: "uploadOther.json"}

    }, addReduce: {

        pageAddReduceByOrderId: {url: "pageAddReduceByOrderId.json"},
        queryAddReduceByOrderId: {url: "queryAddReduceByOrderId.json", demo: true},
        queryAddReduceForPayedByOrderId: {url: "queryAddReduceForPayedByOrderId.json", demo: true},
        queryAddReduceByDecorationPaymentId: {url: "queryAddReduceByDecorationPaymentId.json", demo: true},
        addAddReduce: {url: "addAddReduce.json"},
        updateAddReduce: {url: "updateAddReduce.json"},
        updateAddReduceForAdvance: {url: "updateAddReduceForAdvance.json"},
        deleteAddReduce: {url: "deleteAddReduce.json"},

        submitAddReduce: {url: "submitAddReduce.json"},

        queryAddReduceItemByAddReduceId: {url: "queryAddReduceItemByAddReduceId.json", demo: true},
        queryAddReduceItemByAddReduceIds: {url: "queryAddReduceItemByAddReduceIds.json", demo: true},
        updateAddReduceItem: {url: "updateAddReduceItem.json"},
        deleteAddReduceItem: {url: "deleteAddReduceItem.json"},

    }, approval: {

        pageApprovalByReceiveId: {url: "pageApprovalByReceiveId.json", demo: true},
        queryApprovalByAId: {url: "queryApprovalByAId.json"},
        submitApprovalForCustomer: {url: "submitApprovalForCustomer.json"},
        submitApprovalForVillage: {url: "submitApprovalForVillage.json"},
        submitApprovalForOrderBelong: {url: "submitApprovalForOrderBelong.json"},
        submitApprovalForQuotationDiscount: {url: "submitApprovalForQuotationDiscount.json"},
        submitApprovalForDecorationRefund: {url: "submitApprovalForDecorationRefund.json"},
        submitApprovalForMaterialFullPayment: {url: "submitApprovalForMaterialFullPayment.json"},
        submitApprovalForMaterialRefund: {url: "submitApprovalForMaterialRefund.json"},
        submitApprovalForMaterialOutsideRefund: {url: "submitApprovalForMaterialOutsideRefund.json"},
        submitApprovalForDecorationActivity: {url: "submitApprovalForDecorationActivity.json"},

        approveApproval: {url: "approveApproval.json"},
        refuseApproval: {url: "refuseApproval.json"},

    }, construction: {
        queryAcceptance: {url: "queryAcceptance.json", demo: true},
        updateAcceptance: {url: "updateAcceptance.json"},

        pageDecorationOrderForConstructionSchedule: {url: "pageDecorationOrderForConstructionSchedule.json", demo: true},
        pageDecorationOrderForConstructionScheduleByPlace: {url: "pageDecorationOrderForConstructionScheduleByPlace.json", demo: true},
        pageDecorationOrderForSupervisionByUserId: {url: "pageDecorationOrderForSupervisionByUserId.json", demo: true},
        pageDecorationOrderForQualityByUserId: {url: "pageDecorationOrderForQualityByUserId.json", demo: true},
        pageDecorationOrderForAcceptance: {url: "pageDecorationOrderForAcceptance.json", demo: true},
        queryConstructionScheduleByOrderId: {url: "queryConstructionScheduleByOrderId.json", demo: true},
        queryConstructionScheduleForWorkerNameByOrderId: {url: "queryConstructionScheduleForWorkerNameByOrderId.json", demo: true},
        updateConstructionScheduleByOrderId: {url: "updateConstructionScheduleByOrderId.json"},
        nextConstructionScheduleByOrderId: {url: "nextConstructionScheduleByOrderId.json"},
        checkConstructionScheduleForChanStatus: {url: "checkConstructionScheduleForChanStatus.json"},
        checkFirstPayment: {url: "checkFirstPayment.json"},
        checkSecondPayment: {url: "checkSecondPayment.json"},
        checkFinalyPayment: {url: "checkFinalyPayment.json"},

        queryBricklayConstructionScheduleByOrderId: {url: "queryBricklayConstructionScheduleByOrderId.json", demo: true},
        updateBricklayConstructionSchedule: {url: "updateBricklayConstructionSchedule.json"},
        setBricklayConstructionScheduleForTimeFlag: {url: "setBricklayConstructionScheduleForTimeFlag.json"},
        setBricklayConstructionScheduleForInfo: {url: "setBricklayConstructionScheduleForInfo.json"},
        setBricklayConstructionScheduleForService: {url: "setBricklayConstructionScheduleForService.json"},

        queryBricklayDrawingByCsId: {url: "queryBricklayDrawingByCsId.json", demo: true},
        queryBricklayDrawingByBcsId: {url: "queryBricklayDrawingByBcsId.json"},
        addBricklayDrawing: {url: "addBricklayDrawing.json"},
        deleteBricklayDrawing: {url: "deleteBricklayDrawing.json"},

        queryBricklayConstructionScheduleWorker: {url: "queryBricklayConstructionScheduleWorker.json", demo: true},
        addBricklayConstructionScheduleWorker: {url: "addBricklayConstructionScheduleWorker.json"},
        setBricklayConstructionScheduleWorkerForSalary: {url: "setBricklayConstructionScheduleWorkerForSalary.json"},
        setBricklayConstructionScheduleWorkerForRaty: {url: "setBricklayConstructionScheduleWorkerForRaty.json"},
        deleteBricklayConstructionScheduleWorker: {url: "deleteBricklayConstructionScheduleWorker.json"},

        queryCarpentConstructionScheduleByOrderId: {url: "queryCarpentConstructionScheduleByOrderId.json"},
        updateCarpentConstructionSchedule: {url: "updateCarpentConstructionSchedule.json"},
        setCarpentConstructionScheduleForTimeFlag: {url: "setCarpentConstructionScheduleForTimeFlag.json"},
        setCarpentConstructionScheduleForInfo: {url: "setCarpentConstructionScheduleForInfo.json"},

        queryCarpentDrawingByCsId: {url: "queryCarpentDrawingByCsId.json"},
        queryCarpentDrawingByCcsId: {url: "queryCarpentDrawingByCcsId.json"},
        addCarpentDrawing: {url: "addCarpentDrawing.json"},
        deleteCarpentDrawing: {url: "deleteCarpentDrawing.json"},

        queryCarpentConstructionScheduleWorker: {url: "queryCarpentConstructionScheduleWorker.json"},
        addCarpentConstructionScheduleWorker: {url: "addCarpentConstructionScheduleWorker.json"},
        setCarpentConstructionScheduleWorkerForSalary: {url: "setCarpentConstructionScheduleWorkerForSalary.json"},
        setCarpentConstructionScheduleWorkerForRaty: {url: "setCarpentConstructionScheduleWorkerForRaty.json"},
        deleteCarpentConstructionScheduleWorker: {url: "deleteCarpentConstructionScheduleWorker.json"},

        queryChanConstructionScheduleByOrderId: {url: "queryChanConstructionScheduleByOrderId.json", demo: true},
        updateChanConstructionSchedule: {url: "updateChanConstructionSchedule.json"},
        setChanConstructionScheduleForTimeFlag: {url: "setChanConstructionScheduleForTimeFlag.json"},
        setChanConstructionScheduleForStatus: {url: "setChanConstructionScheduleForStatus.json"},
        setChanConstructionScheduleForInfo: {url: "setChanConstructionScheduleForInfo.json"},
        setChanConstructionScheduleWorker: {url: "setChanConstructionScheduleWorker.json"},
        setChanConstructionScheduleForService: {url: "setChanConstructionScheduleForService.json"},
        setChanConstructionScheduleForSalary: {url: "setChanConstructionScheduleForSalary.json"},

        queryChanDrawingByCsId: {url: "queryChanDrawingByCsId.json", demo: true},
        queryChanDrawingByCcsId: {url: "queryChanDrawingByCcsId.json"},
        addChanDrawing: {url: "addChanDrawing.json"},
        deleteChanDrawing: {url: "deleteChanDrawing.json"},

        queryCleaningConstructionScheduleByOrderId: {url: "queryCleaningConstructionScheduleByOrderId.json", demo: true},
        updateCleaningConstructionSchedule: {url: "updateCleaningConstructionSchedule.json"},
        setCleaningConstructionScheduleForTimeFlag: {url: "setCleaningConstructionScheduleForTimeFlag.json"},
        setCleaningConstructionScheduleForInfo: {url: "setCleaningConstructionScheduleForInfo.json"},

        queryCleaningDrawingByCsId: {url: "queryCleaningDrawingByCsId.json", demo: true},
        queryCleaningDrawingByCcsId: {url: "queryCleaningDrawingByCcsId.json"},
        addCleaningDrawing: {url: "addCleaningDrawing.json"},
        deleteCleaningDrawing: {url: "deleteCleaningDrawing.json"},

        queryCleaningConstructionScheduleWorker: {url: "queryCleaningConstructionScheduleWorker.json", demo: true},
        addCleaningConstructionScheduleWorker: {url: "addCleaningConstructionScheduleWorker.json"},
        setCleaningConstructionScheduleWorkerForSalary: {url: "setCleaningConstructionScheduleWorkerForSalary.json"},
        setCleaningConstructionScheduleWorkerForRaty: {url: "setCleaningConstructionScheduleWorkerForRaty.json"},
        deleteCleaningConstructionScheduleWorker: {url: "deleteCleaningConstructionScheduleWorker.json"},

        queryGroundLevelingConstructionScheduleByOrderId: {url: "queryGroundLevelingConstructionScheduleByOrderId.json", demo: true},
        updateGroundLevelingConstructionSchedule: {url: "updateGroundLevelingConstructionSchedule.json"},
        setGroundLevelingConstructionScheduleForTimeFlag: {url: "setGroundLevelingConstructionScheduleForTimeFlag.json"},
        setGroundLevelingConstructionScheduleForInfo: {url: "setGroundLevelingConstructionScheduleForInfo.json"},

        queryGroundLevelingDrawingByCsId: {url: "queryGroundLevelingDrawingByCsId.json", demo: true},
        queryGroundLevelingDrawingByGlcsId: {url: "queryGroundLevelingDrawingByGlcsId.json"},
        addGroundLevelingDrawing: {url: "addGroundLevelingDrawing.json"},
        deleteGroundLevelingDrawing: {url: "deleteGroundLevelingDrawing.json"},

        queryGroundLevelingConstructionScheduleWorker: {url: "queryGroundLevelingConstructionScheduleWorker.json", demo: true},
        addGroundLevelingConstructionScheduleWorker: {url: "addGroundLevelingConstructionScheduleWorker.json"},
        setGroundLevelingConstructionScheduleWorkerForSalary: {url: "setGroundLevelingConstructionScheduleWorkerForSalary.json"},
        setGroundLevelingConstructionScheduleWorkerForRaty: {url: "setGroundLevelingConstructionScheduleWorkerForRaty.json"},
        deleteGroundLevelingConstructionScheduleWorker: {url: "deleteGroundLevelingConstructionScheduleWorker.json"},

        pageCustomerServiceBackVisit: {url: "pageCustomerServiceBackVisit.json", demo: true},
        addCustomerServiceBackVisit: {url: "addCustomerServiceBackVisit.json"},
        updateCustomerServiceBackVisit: {url: "updateCustomerServiceBackVisit.json"},
        deleteCustomerServiceBackVisit: {url: "deleteCustomerServiceBackVisit.json"},

        pageCustomerServiceComplaint: {url: "pageCustomerServiceComplaint.json", demo: true},
        addCustomerServiceComplaint: {url: "addCustomerServiceComplaint.json"},
        updateCustomerServiceComplaint: {url: "updateCustomerServiceComplaint.json"},
        handleCustomerServiceComplaint: {url: "handleCustomerServiceComplaint.json"},
        deleteCustomerServiceComplaint: {url: "deleteCustomerServiceComplaint.json"},

        pageCustomerServiceGuarantee: {url: "pageCustomerServiceGuarantee.json", demo: true},
        addCustomerServiceGuarantee: {url: "addCustomerServiceGuarantee.json"},
        updateCustomerServiceGuarantee: {url: "updateCustomerServiceGuarantee.json"},
        deleteCustomerServiceGuarantee: {url: "deleteCustomerServiceGuarantee.json"},

        pageInspectionDeductionByOrderId: {url: "pageInspectionDeductionByOrderId.json", demo: true},
        addInspectionDeduction: {url: "addInspectionDeduction.json"},
        deleteInspectionDeduction: {url: "deleteInspectionDeduction.json"},

        pageInspectionRecordByOrderId: {url: "pageInspectionRecordByOrderId.json", demo: true},
        addInspectionRecord: {url: "addInspectionRecord.json"},
        updateInspectionRecord: {url: "updateInspectionRecord.json"},
        deleteInspectionRecord: {url: "deleteInspectionRecord.json"},

        queryOilConstructionScheduleByOrderId: {url: "queryOilConstructionScheduleByOrderId.json", demo: true},
        updateOilConstructionSchedule: {url: "updateOilConstructionSchedule.json"},
        setOilConstructionScheduleForTimeFlag: {url: "setOilConstructionScheduleForTimeFlag.json"},
        setOilConstructionScheduleForInfo: {url: "setOilConstructionScheduleForInfo.json"},

        queryOilDrawingByCsId: {url: "queryOilDrawingByCsId.json", demo: true},
        queryOilDrawingByOcsId: {url: "queryOilDrawingByOcsId.json"},
        addOilDrawing: {url: "addOilDrawing.json"},
        deleteOilDrawing: {url: "deleteOilDrawing.json"},

        queryOilConstructionScheduleWorker: {url: "queryOilConstructionScheduleWorker.json", demo: true},
        addOilConstructionScheduleWorker: {url: "addOilConstructionScheduleWorker.json"},
        setOilConstructionScheduleWorkerForSalary: {url: "setOilConstructionScheduleWorkerForSalary.json"},
        setOilConstructionScheduleWorkerForRaty: {url: "setOilConstructionScheduleWorkerForRaty.json"},
        deleteOilConstructionScheduleWorker: {url: "deleteOilConstructionScheduleWorker.json"},

        queryPutlineConstructionScheduleByOrderId: {url: "queryPutlineConstructionScheduleByOrderId.json", demo: true},
        updatePutlineConstructionSchedule: {url: "updatePutlineConstructionSchedule.json"},
        setPutlineConstructionScheduleForStatus: {url: "setPutlineConstructionScheduleForStatus.json"},
        setPutlineConstructionScheduleForInfo: {url: "setPutlineConstructionScheduleForInfo.json"},
        setPutlineConstructionScheduleWorker: {url: "setPutlineConstructionScheduleWorker.json"},
        setPutlineConstructionScheduleForService: {url: "setPutlineConstructionScheduleForService.json"},
        setPutlineConstructionScheduleForSalary: {url: "setPutlineConstructionScheduleForSalary.json"},

        queryPutlineDrawingByCsId: {url: "queryPutlineDrawingByCsId.json", demo: true},
        addPutlineDrawing: {url: "addPutlineDrawing.json"},
        deletePutlineDrawing: {url: "deletePutlineDrawing.json"},

        pageQualityTestingRecordByOrderId: {url: "pageQualityTestingRecordByOrderId.json"},
        addQualityTestingRecord: {url: "addQualityTestingRecord.json"},
        updateQualityTestingRecord: {url: "updateQualityTestingRecord.json"},
        deleteQualityTestingRecord: {url: "deleteQualityTestingRecord.json"},

        pageReworkByOrderId: {url: "pageReworkByOrderId.json", demo: true},
        addRework: {url: "addRework.json"},
        updateRework: {url: "updateRework.json"},
        deleteRework: {url: "deleteRework.json"},

        queryReworkDrawingByReworkId: {url: "queryReworkDrawingByReworkId.json"},
        addReworkDrawing: {url: "addReworkDrawing.json"},
        deleteReworkDrawingById: {url: "deleteReworkDrawingById.json"},

        queryWaterwayCircuitCheckConstructionScheduleByOrderId: {url: "queryWaterwayCircuitCheckConstructionScheduleByOrderId.json", demo: true},
        updateWaterwayCircuitCheckConstructionSchedule: {url: "updateWaterwayCircuitCheckConstructionSchedule.json"},
        setWaterwayCircuitCheckConstructionScheduleForTimeFlag: {url: "setWaterwayCircuitCheckConstructionScheduleForTimeFlag.json"},
        setWaterwayCircuitCheckConstructionScheduleForInfo: {url: "setWaterwayCircuitCheckConstructionScheduleForInfo.json"},

        queryWaterwayCircuitCheckDrawingByCsId: {url: "queryWaterwayCircuitCheckDrawingByCsId.json", demo: true},
        queryWaterwayCircuitCheckDrawingByWcpcsId: {url: "queryWaterwayCircuitCheckDrawingByWcpcsId.json"},
        addWaterwayCircuitCheckDrawing: {url: "addWaterwayCircuitCheckDrawing.json"},
        deleteWaterwayCircuitCheckDrawing: {url: "deleteWaterwayCircuitCheckDrawing.json"},

        queryWaterwayCircuitCheckConstructionScheduleWorker: {url: "queryWaterwayCircuitCheckConstructionScheduleWorker.json", demo: true},
        addWaterwayCircuitCheckConstructionScheduleWorker: {url: "addWaterwayCircuitCheckConstructionScheduleWorker.json"},
        setWaterwayCircuitCheckConstructionScheduleWorkerForSalary: {url: "setWaterwayCircuitCheckConstructionScheduleWorkerForSalary.json"},
        setWaterwayCircuitCheckConstructionScheduleWorkerForRaty: {url: "setWaterwayCircuitCheckConstructionScheduleWorkerForRaty.json"},
        deleteWaterwayCircuitCheckConstructionScheduleWorker: {url: "deleteWaterwayCircuitCheckConstructionScheduleWorker.json"},

        queryWaterwayCircuitPowerConstructionScheduleByOrderId: {url: "queryWaterwayCircuitPowerConstructionScheduleByOrderId.json", demo: true},
        updateWaterwayCircuitPowerConstructionSchedule: {url: "updateWaterwayCircuitPowerConstructionSchedule.json"},
        setWaterwayCircuitPowerConstructionScheduleForTimeFlag: {url: "setWaterwayCircuitPowerConstructionScheduleForTimeFlag.json"},
        setWaterwayCircuitPowerConstructionScheduleForInfo: {url: "setWaterwayCircuitPowerConstructionScheduleForInfo.json"},
        setWaterwayCircuitPowerConstructionScheduleWorker: {url: "setWaterwayCircuitPowerConstructionScheduleWorker.json"},

        queryWaterwayCircuitPowerDrawingByCsId: {url: "queryWaterwayCircuitPowerDrawingByCsId.json", demo: true},
        queryWaterwayCircuitPowerDrawingByWcpcsId: {url: "queryWaterwayCircuitPowerDrawingByWcpcsId.json"},
        addWaterwayCircuitPowerDrawing: {url: "addWaterwayCircuitPowerDrawing.json"},
        deleteWaterwayCircuitPowerDrawing: {url: "deleteWaterwayCircuitPowerDrawing.json"},

        queryWaterwayCircuitPowerConstructionScheduleWorker: {url: "queryWaterwayCircuitPowerConstructionScheduleWorker.json", demo: true},
        addWaterwayCircuitPowerConstructionScheduleWorker: {url: "addWaterwayCircuitPowerConstructionScheduleWorker.json"},
        setWaterwayCircuitPowerConstructionScheduleWorkerForSalary: {url: "setWaterwayCircuitPowerConstructionScheduleWorkerForSalary.json"},
        setWaterwayCircuitPowerConstructionScheduleWorkerForRaty: {url: "setWaterwayCircuitPowerConstructionScheduleWorkerForRaty.json"},
        deleteWaterwayCircuitPowerConstructionScheduleWorker: {url: "deleteWaterwayCircuitPowerConstructionScheduleWorker.json"}

    }, data: {

        pageBrand: {url: "pageBrand.json", demo: true},
        queryBrand: {url: "queryBrand.json", demo: true},
        queryBrandByBId: {url: "queryBrandByBId.json"},
        queryBrandByBrandId: {url: "queryBrandByBrandId.json"},
        queryBrandByCategoryId: {url: "queryBrandByCategoryId.json", demo: true},
        queryBrandForPinYinName: {url: "queryBrandForPinYinName.json"},
        queryBrandForPinYinNameACategoryName: {url: "queryBrandForPinYinNameACategoryName.json"},
        addBrand: {url: "addBrand.json", server: "communionServer"},
        updateBrand: {url: "updateBrand.json", server: "communionServer"},
        deleteBrandByBIds: {url: "deleteBrandByBIds.json", server: "communionServer"},

        pageCategory: {url: "pageCategory.json", demo: true},
        queryCategory: {url: "queryCategory.json", demo: true},
        queryCategoryByCId: {url: "queryCategoryByCId.json"},
        addCategory: {url: "addCategory.json", server: "communionServer"},
        updateCategory: {url: "updateCategory.json", server: "communionServer"},
        deleteCategoryByCIds: {url: "deleteCategoryByCIds.json", server: "communionServer"},

        pageCustomer: {url: "pageCustomer.json", demo: true},
        queryCustomerById: {url: "queryCustomerById.json"},
        queryCustomerForName: {url: "queryCustomerForName.json"},
        queryCustomerForAdvanceByCustomerId: {url: "queryCustomerForAdvanceByCustomerId.json"},
        checkCustomerForPhone: {url: "checkCustomerForPhone.json"},
        addCustomer: {url: "addCustomer.json", server: "communionServer"},
        updateCustomer: {url: "updateCustomer.json", server: "communionServer"},
        updateCustomerForBalance: {url: "updateCustomerForBalance.json", server: "communionServer"},

        pageVillage: {url: "pageVillage.json", demo: true},
        queryVillage: {url: "queryVillage.json"},
        queryVillageById: {url: "queryVillageById.json"},
        queryVillageForNameByPinyin: {url: "queryVillageForNameByPinyin.json", demo: true},
        addVillage: {url: "addVillage.json", server: "communionServer"},
        updateVillage: {url: "updateVillage.json", server: "communionServer"},
        updateVillageForStatus: {url: "updateVillageForStatus.json", server: "communionServer"},
        updateVillageForPosition: {url: "updateVillageForPosition.json", server: "communionServer"},

    }, department: {

        pageDepartment: {url: "pageDepartment.json", demo: true},
        queryDepartment: {url: "queryDepartment.json", demo: true},
        queryDepartmentById: {url: "queryDepartmentById.json"},
        addDepartment: {url: "addDepartment.json", server: "communionServer"},
        updateDepartment: {url: "updateDepartment.json", server: "communionServer"},
        deleteDepartment: {url: "deleteDepartment.json", server: "communionServer"},

    }, decoration: {

        pageBackVisitByOrderId: {url: "pageBackVisitByOrderId.json"},
        queryBackVisitByOrderId: {url: "queryBackVisitByOrderId.json", demo: true},
        addBackVisit: {url: "addBackVisit.json"},

        queryDecorationActivityByOrderId: {url: "queryDecorationActivityByOrderId.json", demo: true},
        queryDecorationActivityItem: {url: "queryDecorationActivityItem.json", demo: true},
        queryDecorationActivityItemForCouponAVaildByOrderId: {url: "queryDecorationActivityItemForCouponAVaildByOrderId.json"},
        addDecorationActivity: {url: "addDecorationActivity.json"},
        deleteDecorationActivity: {url: "deleteDecorationActivity.json"},
        convertDecorationActivityItem: {url: "convertDecorationActivityItem.json"},
        abateDecorationActivityItem: {url: "abateDecorationActivityItem.json"},
        receiveDecorationActivityItem: {url: "receiveDecorationActivityItem.json"},

        queryDecorationContractByOrderId: {url: "queryDecorationContractByOrderId.json", demo: true},
        saveDecorationContract: {url: "saveDecorationContract.json"},
        generateDecorationContract: {url: "../../generateDecorationContract.json"},
        signDecorationContract: {url: "signDecorationContract.json"},
        resignDecorationContract: {url: "resignDecorationContract.json"},

        pageDecorationOrderForGeneral: {url: "pageDecorationOrderForGeneral.json", demo: true},
        pageDecorationOrderForCommon: {url: "pageDecorationOrderForCommon.json", demo: true},
        pageDecorationOrderForDesigner: {url: "pageDecorationOrderForDesigner.json", demo: true},
        pageDecorationOrderForSalesman: {url: "pageDecorationOrderForSalesman.json", demo: true},
        pageDecorationOrderForMaterial: {url: "pageDecorationOrderForMaterial.json", demo: true},
        pageDecorationOrderForBelong: {url: "pageDecorationOrderForBelong.json", demo: true},
        queryDecorationOrderByVillageIdAHouseNumber: {url: "queryDecorationOrderByVillageIdAHouseNumber.json"},
        queryDecorationOrderForSignedByCustomerId: {url: "queryDecorationOrderForSignedByCustomerId.json"},
        queryDecorationOrderForCondition: {url: "queryDecorationOrderForCondition.json", demo: true},
        queryDecorationOrderForDesignerByOrderId: {url: "queryDecorationOrderForDesignerByOrderId.json", demo: true},
        queryDecorationOrderForCommonByOrderId: {url: "queryDecorationOrderForCommonByOrderId.json", demo: true},
        checkDecorationOrderForExist: {url: "checkDecorationOrderForExist.json"},
        createDecorationOrder: {url: "createDecorationOrder.json"},
        obsoleteDecorationOrder: {url: "obsoleteDecorationOrder.json"},
        terminalDecorationOrder: {url: "terminalDecorationOrder.json"},
        changeDecorationOrderForAdvance: {url: "changeDecorationOrderForAdvance.json"},

        exportDecorationorderByContractTime: {url: "exportDecorationorderByContractTime.json"},

        queryDecorationBelongByOrderId: {url: "queryDecorationBelongByOrderId.json", demo: true},
        queryDecorationBelongForDesignAChangeByOrderId: {url: "queryDecorationBelongForDesignAChangeByOrderId.json", demo: true},
        queryDecorationBelongForDesignByOrderId: {url: "queryDecorationBelongForDesignByOrderId.json"},
        queryDecorationBelongForBusinessnAChangeByOrderId: {url: "queryDecorationBelongForBusinessnAChangeByOrderId.json", demo: true},
        queryDecorationBelongForBusinessnByOrderId: {url: "queryDecorationBelongForBusinessnByOrderId.json"},

        queryOrderDesignPictureByOrderId: {url: "queryOrderDesignPictureByOrderId.json"},
        addOrderDesignPicture: {url: "addOrderDesignPicture.json"},

        queryDecorationPictureByOrderId: {url: "queryDecorationPictureByOrderId.json", demo: true},
        addDecorationPicture: {url: "addDecorationPicture.json"},

    }, drawline:{

        pageDrawLineForPlan: {url: "pageDrawLineForPlan.json", demo: true},
        pageDrawLineForAssign: {url: "pageDrawLineForAssign.json"},
        queryDrawLine: {url: "queryDrawLine.json", demo: true},
        countDrawLineByDate: {url: "countDrawLineByDate.json"},
        resetDrawLine: {url: "resetDrawLine.json"},
        applayDrawLine: {url: "applayDrawLine.json"},
        setDrawLineForSuccess: {url: "setDrawLineForSuccess.json"},
        setDrawLineForFailure: {url: "setDrawLineForFailure.json"},

    }, payment: {

        pagePaymentForHistory: {url: "pagePaymentForHistory.json", demo: true},
        queryPaymentByPaymentId: {url: "queryPaymentByPaymentId.json"},
        collectPayment: {url: "collectPayment.json"},
        confirmPayment: {url: "confirmPayment.json"},
        updatePayment: {url: "updatePayment.json"},
        withdrawPayment: {url: "withdrawPayment.json"},
        convertPayment: {url: "convertPayment.json"},

        pageDecorationPaymentForBaseByOrderId: {url: "pageDecorationPaymentForBaseByOrderId.json", demo: true},
        pageDecorationPaymentForOtherByOrderId: {url: "pageDecorationPaymentForOtherByOrderId.json", demo: true},
        pageDecorationPaymentForCommit: {url: "pageDecorationPaymentForCommit.json", demo: true},
        pageDecorationPaymentForCollect: {url: "pageDecorationPaymentForCollect.json", demo: true},
        pageDecorationPaymentForConfirm: {url: "pageDecorationPaymentForConfirm.json", demo: true},
        pageDecorationPaymentForHistory: {url: "pageDecorationPaymentForHistory.json", demo: true},
        pageDecorationPaymentForChange: {url: "pageDecorationPaymentForChange.json", demo: true},
        queryDecorationPaymentByOrderId: {url: "queryDecorationPaymentByOrderId.json", demo: true},
        queryDecorationPaymentForBaseByOrderId: {url: "queryDecorationPaymentForBaseByOrderId.json", demo: true},
        queryDecorationPaymentByOrderIdAIds: {url: "queryDecorationPaymentByOrderIdAIds.json"},
        queryDecorationPaymentForBaseAConfirmByOrderId: {url: "queryDecorationPaymentForBaseAConfirmByOrderId.json"},
        queryDecorationPaymentForNotInitByDrId: {url: "queryDecorationPaymentForNotInitByDrId.json"},
        queryDecoraionReceiptByDrId: {url: "queryDecoraionReceiptByDrId.json"},
        makeDecorationPayment: {url: "makeDecorationPayment.json"},
        submitDecorationPayment: {url: "submitDecorationPayment.json"},
        addDecorationPaymentForOther: {url: "addDecorationPaymentForOther.json"},
        addDecorationPaymentForRefund: {url: "addDecorationPaymentForRefund.json"},
        convertDecorationPayment: {url: "convertDecorationPayment.json"},
        collectDecorationPayment: {url: "collectDecorationPayment.json"},
        updateDecorationPayment: {url: "updateDecorationPayment.json"},
        updateDecorationPaymentForReferMoney: {url: "updateDecorationPaymentForReferMoney.json"},
        refundDecorationPayment: {url: "refundDecorationPayment.json"},
        refundDecorationPaymentForManage: {url: "refundDecorationPaymentForManage.json"},
        confirmDecorationPayment: {url: "confirmDecorationPayment.json"},

        pageMaterialPayment: {url: "pageMaterialPayment.json"},
        pageMaterialPaymentBySubOrder: {url: "pageMaterialPaymentBySubOrder.json", demo: true},
        pageMaterialPaymentForCollectBySubOrder: {url: "pageMaterialPaymentForCollectBySubOrder.json", demo: true},
        pageMaterialPaymentForConfirmBySubOrder: {url: "pageMaterialPaymentForConfirmBySubOrder.json", demo: true},
        pageMaterialPaymentForNotInitBySubOrder: {url: "pageMaterialPaymentForNotInitBySubOrder.json", demo: true},
        pageMaterialPaymentByMsoId: {url: "pageMaterialPaymentByMsoId.json"},
        pageMaterialPaymentForInitByMsoId: {url: "pageMaterialPaymentForInitByMsoId.json"},
        pageMaterialPaymentByOrderId: {url: "pageMaterialPaymentByOrderId.json"},
        pageMaterialInsidePaymentForInit: {url: "pageMaterialInsidePaymentForInit.json"},
        pageMaterialInsidePaymentForNotInit: {url: "pageMaterialInsidePaymentForNotInit.json"},
        pageMaterialOutsidePaymentForInit: {url: "pageMaterialOutsidePaymentForInit.json", demo: true},
        pageMaterialOutsidePaymentForNotInit: {url: "pageMaterialOutsidePaymentForNotInit.json", demo: true},
        queryMaterialPaymentByOrderId: {url: "queryMaterialPaymentByOrderId.json", demo: true},
        queryMaterialPaymentForInitByMsoId: {url: "queryMaterialPaymentForInitByMsoId.json"},
        queryMaterialPaymentByMsoId: {url: "queryMaterialPaymentByMsoId.json", demo: true},
        queryMaterialPaymentForCouponByMsoId: {url: "queryMaterialPaymentForCouponByMsoId.json"},
        queryMaterialPaymentByMpIds: {url: "queryMaterialPaymentByMpIds.json"},
        queryMaterialPaymentForNotInitByMrId: {url: "queryMaterialPaymentForNotInitByMrId.json"},
        queryMaterialReceiptByMrId: {url: "queryMaterialReceiptByMrId.json"},
        addMaterialPayment: {url: "addMaterialPayment.json"},
        receMaterialPayment: {url: "receMaterialPayment.json"},
        collectMaterialPayment: {url: "collectMaterialPayment.json"},
        collectMaterialInsidePayment: {url: "collectMaterialInsidePayment.json"},
        collectMaterialOutsidePayment: {url: "collectMaterialOutsidePayment.json"},
        updateMaterialInsidePayment: {url: "updateMaterialInsidePayment.json"},
        collectMaterialPayments: {url: "collectMaterialPayments.json"},
        collectMaterialRefundPayment: {url: "collectMaterialRefundPayment.json"},
        collectMaterialInsidePayments: {url: "collectMaterialInsidePayments.json"},
        confirmMaterialPayment: {url: "confirmMaterialPayment.json"},
        confirmMaterialInsidePayment: {url: "confirmMaterialInsidePayment.json"},
        cancelMaterialPayment: {url: "cancelMaterialPayment.json"},
        refundMaterialPayment: {url: "refundMaterialPayment.json"},
        refundMaterialPaymentForCoupon: {url: "refundMaterialPaymentForCoupon.json"},

        exportDecorationPayments: {url: "exportDecorationPayments.json"},

    }, information: {

        pageMessage: {url: "pageMessage.json", demo: true},
        queryMessageForUnRead: {url: "queryMessageForUnRead.json"},
        countMessage: {url: "countMessage.json", demo: true},
        sendMessage: {url: "sendMessage.json"},
        updateMessageForRead: {url: "updateMessageForRead.json"},
        deleteMessageById: {url: "deleteMessageById.json"},
        deleteMessageByIds: {url: "deleteMessageByIds.json"},

        pageNotice: {url: "pageNotice.json", demo: true},
        pageNoticeForDeptAValid: {url: "pageNoticeForDeptAValid.json", demo: true},
        queryNoticeForValid: {url: "queryNoticeForValid.json"},
        queryNoticeById: {url: "queryNoticeById.json"},
        addNotice: {url: "addNotice.json"},
        updateNotice: {url: "updateNotice.json"},
        deleteNotice: {url: "deleteNotice.json"},

        pageActivity: {url: "pageActivity.json", demo: true},
        queryActivityForValid: {url: "queryActivityForValid.json", demo: true},
        queryActivityItemByAId: {url: "queryActivityItemByAId.json", demo: true},
        addActivity: {url: "addActivity.json"},
        addActivityItem: {url: "addActivityItem.json"},
        updateActivity: {url: "updateActivity.json"},
        updateActivityItem: {url: "updateActivityItem.json"},
        deleteActivityItemByAiId: {url: "deleteActivityItemByAiId.json"},

    }, log: {

        pageActionLog: {url: "pageActionLog.json"},
        pageLoginLog: {url: "pageLoginLog.json", demo: true},

    }, material: {

        queryMaterialBrand: {url: "queryMaterialBrand.json"},
        queryMaterialBrandById: {url: "queryMaterialBrandById.json"},
        queryMaterialBrandForName: {url: "queryMaterialBrandForName.json"},
        queryMaterialBrandForNameAType: {url: "queryMaterialBrandForNameAType.json"},
        addMaterialBrand: {url: "addMaterialBrand.json"},
        updateMaterialBrand: {url: "updateMaterialBrand.json"},
        deleteMaterialBrandByIds: {url: "deleteMaterialBrandByIds.json"},

        queryMaterialBrandRight: {url: "queryMaterialBrandRight.json", demo: true},
        saveMaterialBrandRight: {url: "saveMaterialBrandRight.json"},

        pageMaterialInside: {url: "pageMaterialInside.json"},
        pageMaterialInsideByUserId: {url: "pageMaterialInsideByUserId.json"},
        addMaterialInside: {url: "addMaterialInside.json"},
        updateMaterialInside: {url: "updateMaterialInside.json"},
        deleteMaterialInsideByMiIds: {url: "deleteMaterialInsideByMiIds.json"},

        pageMaterialModel: {url: "pageMaterialModel.json", demo: true},
        queryMaterialModel: {url: "queryMaterialModel.json"},
        queryMaterialModelById: {url: "queryMaterialModelById.json", demo: true},
        queryMaterialModelByNo: {url: "queryMaterialModelByNo.json"},
        queryMaterialModelForAllByName: {url: "queryMaterialModelForAllByName.json", demo: true},
        queryMaterialModelForAllByNo: {url: "queryMaterialModelForAllByNo.json"},
        addMaterialModel: {url: "addMaterialModel.json"},
        updateMaterialModel: {url: "updateMaterialModel.json"},
        updateMaterialModelForStatus: {url: "updateMaterialModelForStatus.json"},
        deleteMaterialModelByIds: {url: "deleteMaterialModelByIds.json"},

        pageMaterialSubOrderForPreBalance: {url: "pageMaterialSubOrderForPreBalance.json", demo: true},
        pageMaterialSubOrderForPostBalance: {url: "pageMaterialSubOrderForPostBalance.json", demo: true},
        updateMaterialSubOrderForPreBalancePT: {url: "updateMaterialSubOrderForPreBalancePT.json"},
        preBalanceMaterialSubOrder: {url: "preBalanceMaterialSubOrder.json"},
        postBalanceMaterialSubOrder: {url: "postBalanceMaterialSubOrder.json"},

        pageMaterialOutside: {url: "pageMaterialOutside.json", demo: true},
        pageMaterialOutsideByUserId: {url: "pageMaterialOutsideByUserId.json", demo: true},
        addMaterialOutside: {url: "addMaterialOutside.json"},
        updateMaterialOutside: {url: "updateMaterialOutside.json"},
        confirmMaterialOutsideByIds: {url: "confirmMaterialOutsideByIds.json"},
        deleteMaterialOutsideByIds: {url: "deleteMaterialOutsideByIds.json"},

        pageMaterialSubOrder: {url: "pageMaterialSubOrder.json"},
        pageMaterialSubOrderByUserId: {url: "pageMaterialSubOrderByUserId.json", demo: true},
        pageMaterialSubOrderByOrderId: {url: "pageMaterialSubOrderByOrderId.json"},
        pageMaterialSubOrderByOrderIdADeptId: {url: "pageMaterialSubOrderByOrderIdADeptId.json"},
        queryMaterialSubOrderByMsoId: {url: "queryMaterialSubOrderByMsoId.json", demo: true},
        addMaterialSubOrder: {url: "addMaterialSubOrder.json"},
        updateMaterialSubOrderForCoupon: {url: "updateMaterialSubOrderForCoupon.json"},
        updateMaterialSubOrderForMaling: {url: "updateMaterialSubOrderForMaling.json"},
        deliverMaterialSubOrder: {url: "deliverMaterialSubOrder.json"},
        deleteMaterialSubOrder: {url: "deleteMaterialSubOrder.json"},

        pageMaterialSubOrderItem: {url: "pageMaterialSubOrderItem.json"},
        queryMaterialSubOrderItemByOrderId: {url: "queryMaterialSubOrderItemByOrderId.json"},
        queryMaterialSubOrderItemByMsoId: {url: "queryMaterialSubOrderItemByMsoId.json", demo: true},
        queryMaterialSubOrderItemByMsoiIds: {url: "queryMaterialSubOrderItemByMsoiIds.json"},
        queryMaterialSubOrderItemForSaleByMsoiId: {url: "queryMaterialSubOrderItemForSaleByMsoiId.json", demo: true},
        queryMaterialSubOrderItemForNoPackageByMsoiId: {url: "queryMaterialSubOrderItemForNoPackageByMsoiId.json"},
        queryMaterialSubOrderItemForNameByName: {url: "queryMaterialSubOrderItemForNameByName.json", demo: true},
        queryMaterialSubOrderItemForNameByNo: {url: "queryMaterialSubOrderItemForNameByNo.json"},
        addMaterialSubOrderItem: {url: "addMaterialSubOrderItem.json"},
        updateMaterialSubOrderItemForModel: {url: "updateMaterialSubOrderItemForModel.json"},
        updateMaterialSubOrderItemForPackage: {url: "updateMaterialSubOrderItemForPackage.json"},
        updateMaterialSubOrderItemForPrePT: {url: "updateMaterialSubOrderItemForPrePT.json"},
        updateMaterialSubOrderItemForPostPT: {url: "updateMaterialSubOrderItemForPostPT.json"},
        refundMaterialSubOrderItemForModel: {url: "refundMaterialSubOrderItemForModel.json"},
        refundMaterialSubOrderItemForPackage: {url: "refundMaterialSubOrderItemForPackage.json"},
        changeMaterialSubOrderItemForCaclType: {url: "changeMaterialSubOrderItemForCaclType.json"},
        deleteMaterialSubOrderItem: {url: "deleteMaterialSubOrderItem.json"},

        queryMaterialSubOrderRefund: {url: "queryMaterialSubOrderRefund.json", demo: true},
        queryMaterialSubOrderRefundByMsoIdAIdent: {url: "queryMaterialSubOrderRefundByMsoIdAIdent.json"},
        cancelMaterialSubOrderRefundForModel: {url: "cancelMaterialSubOrderRefundForModel.json"},
        cancelMaterialSubOrderRefundForPackage: {url: "cancelMaterialSubOrderRefundForPackage.json"},

        pageMaterialType: {url: "pageMaterialType.json"},
        queryMaterialType: {url: "queryMaterialType.json"},
        queryMaterialTypeById: {url: "queryMaterialTypeById.json"},
        addMaterialType: {url: "addMaterialType.json"},
        updateMaterialType: {url: "updateMaterialType.json"},
        deleteMaterialTypeByIds: {url: "deleteMaterialTypeByIds.json"}

    },personel: {

        pageUser: {url: "pageUser.json", demo: true},
        pageUserForResetPassword: {url: "pageUserForResetPassword.json", demo: true},
        queryUserByLoginId: {url: "queryUserByLoginId.json"},
        queryUserByUserId: {url: "queryUserByUserId.json", demo: true},
        queryUserForSelfByUserId: {url: "queryUserForSelfByUserId.json", demo: true},
        queryUserByOldUserId: {url: "queryUserByOldUserId.json"},
        queryUserForNameByPinyinName: {url: "queryUserForNameByPinyinName.json"},
        queryUserForNameByDuty: {url: "queryUserForNameByDuty.json", demo: true},
        queryUserForNameByDutys: {url: "queryUserForNameByDutys.json", demo: true},
        queryUserForNameByDutyADept: {url: "queryUserForNameByDutyADept.json"},
        queryUserForNameByDutysADept: {url: "queryUserForNameByDutysADept.json"},
        queryUserForNameByDutysAO: {url: "queryUserForNameByDutysAO.json"},
        queryUserForNameByDutysAODept: {url: "queryUserForNameByDutysAODept.json"},
        addUser: {url: "addUser.json", server: "communionServer"},
        saveUserForBaseInfo: {url: "saveUserForBaseInfo.json", server: "communionServer"},
        updateUser: {url: "updateUser.json", server: "communionServer"},
        updateUserForAdvance: {url: "updateUserForAdvance.json", server: "communionServer"},
        resetPassword: {url: "resetPassword.json", server: "communionServer"},
        changePassword: {url: "changePassword.json", server: "communionServer"},
        deleteUserByIds: {url: "deleteUserByIds.json", server: "communionServer"},

        pageUserContractByUserId: {url: "pageUserContractByUserId.json"},
        addUserContract: {url: "addUserContract.json", server: "communionServer"},
        updateUserContract: {url: "updateUserContract.json", server: "communionServer"},
        deleteUserContract: {url: "deleteUserContract.json", server: "communionServer"},

        pageUserExperienceByUserId: {url: "pageUserExperienceByUserId.json"},
        addUserExperience: {url: "addUserExperience.json", server: "communionServer"},
        updateUserExperience: {url: "updateUserExperience.json", server: "communionServer"},
        deleteUserExperience: {url: "deleteUserExperience.json", server: "communionServer"},

        pageUserSalary: {url: "pageUserSalary.json"},
        pageUserSalaryByUserId: {url: "pageUserSalaryByUserId.json"},
        addUserSalary: {url: "addUserSalary.json"},
        updateUserSalary: {url: "updateUserSalary.json"},
        deleteUserSalary: {url: "deleteUserSalary.json"},

    }, quotation: {

        queryQuotationClassification: {url: "queryQuotationClassification.json", demo: true},
        queryQuotationBigCategory: {url: "queryQuotationBigCategory.json", demo: true},
        queryQuotationSmallCategory: {url: "queryQuotationSmallCategory.json", demo: true},
        queryQuotationType: {url: "queryQuotationType.json", demo: true},

        pageQuotationVersion: {url: "pageQuotationVersion.json", demo: true},
        queryQuotationVersion: {url: "queryQuotationVersion.json", demo: true},
        queryQuotationVersionByVersionId: {url: "queryQuotationVersionByVersionId.json"},
        addQuotationVersion: {url: "addQuotationVersion.json"},
        updateQuotationVersion: {url: "updateQuotationVersion.json"},
        copyQuotationVersion: {url: "copyQuotationVersion.json"},

        pageFunctionArea: {url: "pageFunctionArea.json", demo: true},
        queryFunctionAreaByIdAVersionId: {url: "queryFunctionAreaByIdAVersionId.json"},
        queryFunctionAreaByVersionId: {url: "queryFunctionAreaByVersionId.json", demo: true},
        addFunctionArea: {url: "addFunctionArea.json"},
        updateFunctionArea: {url: "updateFunctionArea.json"},
        deleteFunctionArea: {url: "deleteFunctionArea.json"},

        pageQuotationItem: {url: "pageQuotationItem.json", demo: true},
        pageQuotationItemByVersionId: {url: "pageQuotationItemByVersionId.json", demo: true},
        queryQuotationItemByItemIdAVersionId: {url: "queryQuotationItemByItemIdAVersionId.json"},
        addQuotationItem: {url: "addQuotationItem.json"},
        updateQuotationItem: {url: "updateQuotationItem.json"},
        updateQuotationItemForStatus: {url: "updateQuotationItemForStatus.json"},
        updateQuotationItemForDiscount: {url: "updateQuotationItemForDiscount.json"},

        queryFunctionAreaItemByFunctionAreaId: {url: "queryFunctionAreaItemByFunctionAreaId.json", demo: true},
        addFunctionAreaItem: {url: "addFunctionAreaItem.json"},
        deleteFunctionAreaItemByIds: {url: "deleteFunctionAreaItemByIds.json"},

        pageSystemDefineItem: {url: "pageSystemDefineItem.json", demo: true},
        pageSystemDefineItemForEnable: {url: "pageSystemDefineItemForEnable.json", demo: true},
        querySystemDefineItemByItemId: {url: "querySystemDefineItemByItemId.json"},
        addSystemDefineItem: {url: "addSystemDefineItem.json"},
        updateSystemDefineItem: {url: "updateSystemDefineItem.json"},
        updateSystemDefineItemForStatus: {url: "updateSystemDefineItemForStatus.json"},
        updateSystemDefineItemForDiscount: {url: "updateSystemDefineItemForDiscount.json"},
        deleteSystemDefineItemByIds: {url: "deleteSystemDefineItemByIds.json"},

        queryQuotationByOrderId: {url: "queryQuotationByOrderId.json", demo: true},
        queryQuotationForDefaultByOrderId: {url: "queryQuotationForDefaultByOrderId.json", demo: true},
        queryQuotationById: {url: "queryQuotationById.json", demo: true},
        queryQuotationForStatusByOrderId: {url: "queryQuotationForStatusByOrderId.json", demo: true},
        queryQuotationForConfig: {url: "queryQuotationForConfig.json", demo: true},
        checkQuotationForStatusByOrderId: {url: "checkQuotationForStatusByOrderId.json"},
        addQuotation: {url: "addQuotation.json"},
        updateQuotation: {url: "updateQuotation.json"},
        updateQuotationForAdvance: {url: "updateQuotationForAdvance.json"},
        deleteQuotationById: {url: "deleteQuotationById.json"},
        replicaQuotation: {url: "replicaQuotation.json"},
        copyQuotation: {url: "copyQuotation.json"},
        changeQuotationForDefault: {url: "changeQuotationForDefault.json"},

        queryQuotationFunctionAreaForCommonByQuotationId: {url: "queryQuotationFunctionAreaForCommonByQuotationId.json", demo: true},
        queryQuotationFunctionAreaByQuotationId: {url: "queryQuotationFunctionAreaByQuotationId.json", demo: true},
        addQuotationFuctionAreaByFunctionAreaIds: {url: "addQuotationFuctionAreaByFunctionAreaIds.json"},
        updateQuotationFunctionArea: {url: "updateQuotationFunctionArea.json"},
        deleteQuotationFunctionArea: {url: "deleteQuotationFunctionArea.json"},

        queryQuotationFunctionAreaItemByQuotationFunctionAreaId: {url: "queryQuotationFunctionAreaItemByQuotationFunctionAreaId.json"},
        updateQuotationFunctionAreaItem: {url: "updateQuotationFunctionAreaItem.json"},
        updateQuotationFunctionAreaItemForSpec: {url: "updateQuotationFunctionAreaItemForSpec.json"},
        deleteQuotationFunctionAreaItem: {url: "deleteQuotationFunctionAreaItem.json"},

    }, report: {

        queryRankForPlace: {url: "queryRankForPlace.json", demo: true},

        queryDecorationDesignerRank: {url: "queryDecorationDesignerRank.json"},
        queryDecorationDesignerDepartmentRank: {url: "queryDecorationDesignerDepartmentRank.json"},
        queryDecorationDesignerRegionRank: {url: "queryDecorationDesignerRegionRank.json"},
        decorationDesignerRank: {url: "decorationDesignerRank.json", demo: true},
        decorationDesignerDepartmentRank: {url: "decorationDesignerDepartmentRank.json", demo: true},
        decorationDesignerRegionRank: {url: "decorationDesignerRegionRank.json", demo: true},

        queryMaterialDesignerRank: {url: "queryMaterialDesignerRank.json"},
        queryMaterialDesignerDepartmentRank: {url: "queryMaterialDesignerDepartmentRank.json"},
        queryMaterialDesignerRegionRank: {url: "queryMaterialDesignerRegionRank.json"},
        materialDesignerRank: {url: "materialDesignerRank.json", demo: true},
        materialDesignerDepartmentRank: {url: "materialDesignerDepartmentRank.json", demo: true},
        materialDesignerRegionRank: {url: "materialDesignerRegionRank.json", demo: true},

        queryZaterialDesignerRank: {url: "queryZaterialDesignerRank.json"},
        queryZaterialDesignerDepartmentRank: {url: "queryZaterialDesignerDepartmentRank.json"},
        queryZaterialDesignerRegionRank: {url: "queryZaterialDesignerRegionRank.json"},
        zaterialDesignerRank: {url: "zaterialDesignerRank.json", demo: true},
        zaterialDesignerDepartmentRank: {url: "zaterialDesignerDepartmentRank.json", demo: true},
        zaterialDesignerRegionRank: {url: "zaterialDesignerRegionRank.json", demo: true},

        materialTypeReport: {url: "materialTypeReport.json", demo: true},
        materialBrandReport: {url: "materialBrandReport.json", demo: true},
        materialDepartmentReport: {url: "materialDepartmentReport.json", demo: true},
        designerReport: {url: "designerReport.json"},
        designerDeportmentReport: {url: "designerDeportmentReport.json"},
        designerRegionReport: {url: "designerRegionReport.json"},
        countMaterialType: {url: "countMaterialType.json", demo: true},
        countMaterialBrand: {url: "countMaterialBrand.json", demo: true},
        countDesigner: {url: "countDesigner.json", demo: true},
        countDesignerDepartment: {url: "countDesignerDepartment.json", demo: true},
        countDesignerRegion: {url: "countDesignerRegion.json", demo: true},

    }, right: {
        queryDecorationOrderDesignDepartmentRightByUserId: {url: "queryDecorationOrderDesignDepartmentRightByUserId.json", demo: true},
        queryDecorationOrderSalesmanDepartmentRightByUserId: {url: "queryDecorationOrderSalesmanDepartmentRightByUserId.json", demo: true},
        queryDecorationOrderStatusRightByUserId: {url: "queryDecorationOrderStatusRightByUserId.json", demo: true},

        updateDecorationOrderDesignDepartmentRight: {url: "updateDecorationOrderDesignDepartmentRight.json"},
        updateDecorationOrderSalesmanDepartmentRight: {url: "updateDecorationOrderSalesmanDepartmentRight.json"},
        updateDecorationOrderStatusRight: {url: "updateDecorationOrderStatusRight.json"},

    }, salary: {
        pageDesignerSalary: {url: "pageDesignerSalary.json"},
        pageDesignerSalaryForInit: {url: "pageDesignerSalaryForInit.json"},
        pageDesignerSalaryForPayOff: {url: "pageDesignerSalaryForPayOff.json"},
        pageDesignerSalaryForUnPayOff: {url: "pageDesignerSalaryForUnPayOff.json"},
        pageDesignerPreBalanceSalary: {url: "pageDesignerPreBalanceSalary.json"},
        pageDesignerPostBalanceSalary: {url: "pageDesignerPostBalanceSalary.json"},
        pageDesignerOutsideSalary: {url: "pageDesignerOutsideSalary.json"},
        pageDesignerDeductSalary: {url: "pageDesignerDeductSalary.json"},
        payDesignerSalary: {url: "payDesignerSalary.json"},
        payoffDesignerSalary: {url: "payoffDesignerSalary.json"},
        unpayoffDesignerSalary: {url: "unpayoffDesignerSalary.json"},

        pageVenderBalance: {url: "pageVenderBalance.json"},
        pageVenderBalanceForInit: {url: "pageVenderBalanceForInit.json"},
        pageVenderBalanceForPayOff: {url: "pageVenderBalanceForPayOff.json"},
        payVenderBalance: {url: "payVenderBalance.json"},

        pageWorkerSalaryForInit: {url: "pageWorkerSalaryForInit.json"},
        pageWorkerSalaryForPayOff: {url: "pageWorkerSalaryForPayOff.json"},
        pageWorkerSalaryForUnPayOff: {url: "pageWorkerSalaryForUnPayOff.json"},
        pageWorkerBaseSalary: {url: "pageWorkerBaseSalary.json"},
        pageWorkerBaseSalaryByOrderIdAUserId: {url: "pageWorkerBaseSalaryByOrderIdAUserId.json"},
        pageWorkerBaseSalaryForPass: {url: "pageWorkerBaseSalaryForPass.json"},
        pageWorkerDeductSalaryByOrderIdAUserId: {url: "pageWorkerDeductSalaryByOrderIdAUserId.json"},
        pageWorkerDeductSalaryForPersonal: {url: "pageWorkerDeductSalaryForPersonal.json"},
        queryWorkerBaseSalary: {url: "queryWorkerBaseSalary.json"},
        payWorkerSalary: {url: "payWorkerSalary.json"},
        payoffWorkerSalary: {url: "payoffWorkerSalary.json"},
        unPayoffWorkerSalary: {url: "unPayoffWorkerSalary.json"},
        addWorkerBaseSalary: {url: "addWorkerBaseSalary.json"},
        addWorkerDeductSalary: {url: "addWorkerDeductSalary.json"},
        updateWorkerBaseSalary: {url: "updateWorkerBaseSalary.json"},
        updateWorkerDeductSalary: {url: "updateWorkerDeductSalary.json"},
        passWorkerBaseSalary: {url: "passWorkerBaseSalary.json"},
        passWorkerDeductSalary: {url: "passWorkerDeductSalary.json"},
        confirmWorkerBaseSalary: {url: "confirmWorkerBaseSalary.json"},
        confirmWorkerDeductSalary: {url: "confirmWorkerDeductSalary.json"},
        cancelWorkerBaseSalaryToInit: {url: "cancelWorkerBaseSalaryToInit.json"},
        cancelWorkerDeductSalaryToInit: {url: "cancelWorkerDeductSalaryToInit.json"},
        cancelWorkerBaseSalaryToConfirm: {url: "cancelWorkerBaseSalaryToConfirm.json"},
        cancelWorkerDeductSalaryToConfirm: {url: "cancelWorkerDeductSalaryToConfirm.json"},
        deleteWorkerBaseSalary: {url: "deleteWorkerBaseSalary.json"},
        deleteWorkerDeductSalary: {url: "deleteWorkerDeductSalary.json"},

    }, system: {
        pageCity: {url: "pageCity.json", demo: true},
        queryCity: {url: "queryCity.json", demo: true},
        queryCityById: {url: "queryCityById.json"},
        queryCityByRegionId: {url: "queryCityByRegionId.json", demo: true},
        addCity: {url: "addCity.json", server: "communionServer"},
        updateCity: {url: "updateCity.json", server: "communionServer"},
        deleteCityByIds: {url: "deleteCityByIds.json", server: "communionServer"},

        pageCityProper: {url: "pageCityProper.json", demo: true},
        queryCityProper: {url: "queryCityProper.json"},
        queryCityProperById: {url: "queryCityProperById.json"},
        queryCityProperByCityId: {url: "queryCityProperByCityId.json", demo: true},
        addCityProper: {url: "addCityProper.json", server: "communionServer"},
        updateCityProper: {url: "updateCityProper.json", server: "communionServer"},
        deleteCityProper: {url: "deleteCityProper.json", server: "communionServer"},

        queryFunctionByModuleId: {url: "queryFunctionByModuleId.json", demo: true},

        queryModule: {url: "queryModule.json", demo: true},

        pageRegion: {url: "pageRegion.json", demo: true},
        queryRegion: {url: "queryRegion.json", demo: true},
        queryRegionById: {url: "queryRegionById.json"},
        addRegion: {url: "addRegion.json", server: "communionServer"},
        updateRegion: {url: "updateRegion.json", server: "communionServer"},
        deleteRegion: {url: "deleteRegion.json", server: "communionServer"},

        pageRole: {url: "pageRole.json", demo: true},
        queryRole: {url: "queryRole.json", demo: true},
        queryRoleById: {url: "queryRoleById.json"},
        queryRoleByName: {url: "queryRoleByName.json"},
        addRole: {url: "addRole.json", server: "communionServer"},
        updateRole: {url: "updateRole.json", server: "communionServer"},
        deleteRoleByIds: {url: "deleteRoleByIds.json", server: "communionServer"},

        queryRoleRight: {url: "queryRoleRight.json", demo: true},
        updateRoleRight: {url: "updateRoleRight.json", server: "communionServer"},

        querySubFunctionByFunctionId: {url: "querySubFunctionByFunctionId.json", demo: true},
        querySubFunctionLikeName: {url: "querySubFunctionLikeName.json"},

        pageSubFunctionAction: {url: "pageSubFunctionAction.json", demo: true},
        querySubFunctionActionByName: {url: "querySubFunctionActionByName.json"},
        addSubFunctionAction: {url: "addSubFunctionAction.json", server: "communionServer"},
        updateSubFunctionAction: {url: "updateSubFunctionAction.json", server: "communionServer"},
        deleteSubFunctionAction: {url: "deleteSubFunctionAction.json", server: "communionServer"},

        pageUserApprove: {url: "pageUserApprove.json", demo: true},
        queryApproveUserForNameByType: {url: "queryApproveUserForNameByType.json"},
        addUserApprove: {url: "addUserApprove.json"},
        updateUserApprove: {url: "updateUserApprove.json"},
        deleteUserApprove: {url: "deleteUserApprove.json"},

    }
}
